#!/bin/sh
ssh ubuntu@34.217.109.194 <<EOF
    cd ci-cd-jenkins
    git pull origin develop
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF